### ISSUE TITLE
1.18 Fabric port?

### ISSUE THREAD

**Issue by embeddedt** [MightyPirates/Scannable#102]
Hello, I've been using your mod in 1.12 for a while and absolutely love it. Recently, I've been looking into making a Fabric 1.18 pack and your mod was one I really wanted to include. So, I ported it to Fabric (source code [here](https://github.com/embeddedt/Scannable-Fabric)).

Is this something you would be willing to entertain upstream/publish to the CurseForge page?

**Comment by fnuecke** [comment]
Hey, that's super neat! Sure, I'd be happy to have a Fabric version of the mod up for people. If you'd like, I can make a branch to PR it into?

**Comment by embeddedt** [comment]
Sounds good to me! I've also ported to 1.18.2 in the meantime.

**Comment by fnuecke** [comment]
Awesome! Branch exists: https://github.com/MightyPirates/Scannable/tree/1.18-fabric

**Comment by fnuecke** [comment]
Release is up :)

**Comment by embeddedt** [comment]
Great! Feel free to ping me if someone opens a Fabric-specific bug and I'll take a look.
