### ISSUE TITLE
Scannable Crash at 1.18.2

### ISSUE THREAD

**Issue by berlinlmaoo** [MightyPirates/Scannable#103]

**Comment by berlinlmaoo** [comment]
when i open my minecraft got crash

**Comment by fnuecke** [comment]
Please provide a crash report.

**Comment by berlinlmaoo** [comment]
[crash-2022-04-18_00.51.07-client.txt](https://github.com/MightyPirates/Scannable/files/8502166/crash-2022-04-18_00.51.07-client.txt)

**Comment by fnuecke** [comment]
Scannable does not appear in that stacktrace, and I don't see how it could be related to it. The only non-vanilla thing that pops up in there, from what I can tell, is HammerLib. Maybe try updating that/try without that.
