### ISSUE TITLE
Graphics glitch with Optifine + shaders

### ISSUE THREAD

**Issue by Icarius89** [MightyPirates/Scannable#109]
Ive tried a few shaderpacks on 1.12.2 playing ftb interactions scanner produces graphical glitches.

shader: https://www.curseforge.com/minecraft/customization/projectluma/files
Optfine 1.12.2 HD_U_G5

**Comment by Icarius89** [comment]
picture of the glitch:
![Screenshot_3](https://user-images.githubusercontent.com/63921087/165585844-de92f7d9-08f0-46a5-bd91-936ba3c2d527.png)

**Comment by fnuecke** [comment]
Sorry, not supporting 1.12 anymore.
