### ISSUE TITLE
Fabric port doesn't detect certain ores with either common ores or rare ores modules

### ISSUE THREAD

**Issue by G93d14** [MightyPirates/Scannable#112]
The default config file has the tags for lapis, gold, and diamond ores missing from both the ores tags. I'm not sure if that is why it didn't detect them, but I had to use a block module with gold ores in it before the scanner would detect the ore.

**Comment by G93d14** [comment]
[scannable-common config.zip](https://github.com/MightyPirates/Scannable/files/8790808/scannable-common.config.zip)
 here's both the default config, and my edit to make it include those three ores

**Comment by G93d14** [comment]
Emerald ores were missing too.

**Comment by fnuecke** [comment]
All ores (based on the ores tag, `c:ores`) not listed in common should automatically picked up by the rare ore scanner.

Are these blocks missing that tag?

**Comment by G93d14** [comment]
I don't know how to check that, but I do know the scanner tool wasn't detecting them until I manually added them in.
