### ISSUE TITLE
Fabric Edition 1.18.2 Using Scanner does nothing

### ISSUE THREAD

**Issue by NameLord** [MightyPirates/Scannable#113]
I have disabled the energy consumption since i im not using any of the mods that adds tech..
But is there incompatibilities with Sodium , indium , lithium , Phosphor ?
because when i hold right click to charge and the release automatically at 100% it doesn't do anything.
![image](https://user-images.githubusercontent.com/27507408/179579797-a99724f0-9313-4546-a8eb-5bab5c24e4cc.png)

**Comment by LumaLivy** [comment]
I came here to mention that I'm also facing this issue on 1.19 + Forge, and disabling rubidium (and oculus, because it depends on rubidium) made the scanner work again. It's probably an incompatibility with sodium/rubidium. No errors are logged while using the scanner while it's not working.

**Comment by fnuecke** [comment]
I'm afraid I don't have the time to support compatibility with shader/render-customization mods.  Sorry!
