### ISSUE TITLE
1.19.2 - Scanned Ores doesn't appear.

### ISSUE THREAD

**Issue by SireAwfulThe1st** [MightyPirates/Scannable#116]
Seems like there's a mod or something that interferes with the shaders used so that scanned blocks and entities doesn't get highlighted at all, I'm not sure if it's because of Rubidium or a resource pack I'm using, I tried running only scannable as a mod and seems like it works perfectly, Could you perhaps investigate this issue? I'd also would love tae give you my personal modpack incase you're willing tae investigate by yourself, otherwise please do help me know what is causing this arguably big annoyance of an issue.

**Comment by MitchellMarx** [comment]
When using oculus-mc1.19.2-1.2.8 and rubidium-0.6.2 with shaders enabled causes this issue. Disabling shaders allows the scanner to work correctly.

**Comment by fnuecke** [comment]
Sorry, supporting shader mods is sadly not something I have time for.
