### ISSUE TITLE
1.16.5 light level is too insane

### ISSUE THREAD

**Issue by deprale** [MightyPirates/Scannable#117]
Make an option to set the transparency or opacity idk cause when I'm mining in a cave or something I literally CAN NOT SEE where the hell I'm going cause the blocks are just way toooooooo bright.

![image](https://user-images.githubusercontent.com/33827235/198776997-3edf4931-b039-4a51-b887-543778dbcb92.png)

**Comment by fnuecke** [comment]
Sorry, don't have time to support versions older MC.  You might have some success adjusting the colors in the config to less "bright" values.
