### ISSUE TITLE
1.18.2 Fabric doesn't register fe from Create tesla.

### ISSUE THREAD

**Issue by WDLBPH** [MightyPirates/Scannable#118]
1.18.2 on fabric, [1.7.7+67bcbed.jar](https://www.curseforge.com/minecraft/mc-mods/scannable/files/3781153) the scanner doesn't take fe from the Create Crafts and Additions version -20220914a.jar tesla coil charger, and is therefore useless on multiplayer survival. Also reported to the Curseforge page and the Create Crafts and Additions pages.

**Comment by fnuecke** [comment]
Sorry, don't have the time to support versions for older MC versions anymore.
