### ISSUE TITLE
No scan wave and ore outlines

### ISSUE THREAD

**Issue by VozDeOuro** [MightyPirates/Scannable#119]
i am using Oculus and iris with Forge 43.1.57
when i put some kind of shaders (first image) the only thing that works is the blue i with the name of the ore
when i turn off the shaders (image 2) everything works as expected

![image](https://user-images.githubusercontent.com/36045463/210198705-ffda40ff-30cb-491b-b400-5aabaaf922bd.png)
![image](https://user-images.githubusercontent.com/36045463/210198736-0fca4b5a-d602-433e-a1f0-9c2ebe44db33.png)

**Comment by Expack3** [comment]
I get an identical issue with an identical workaround using Minecraft Java 1.19.2, Forge 43.2.3, Oculus 1.8.2a, and Rubidium 0.6.2.

**Comment by serratedserenade** [comment]
Seems like this doesn't work well with shaders, should probably have some shader compatible mode of a sort

**Comment by fnuecke** [comment]
As mentioned in other issues, I'm afraid I don't have the time to actively support shader mods.
