### ISSUE TITLE
Failed to create mod instance. ModID: scannable, class li.cil.scannable.common.forge.CommonSetupForge

### ISSUE THREAD

**Issue by Zemogiter** [MightyPirates/Scannable#121]
[crash-2023-01-18_19.03.12-fml.txt](https://github.com/MightyPirates/Scannable/files/10449309/crash-2023-01-18_19.03.12-fml.txt)
Minecraft version: 1.19.3
Forge version: 44.1.5
Mod version: scannable-MC1.19.3-forge-1.7.7+457fea6

**Comment by fnuecke** [comment]
You'll also need Architectury.  Forgot the dependency declaration for Forge, added in 1.7.8.
