### ISSUE TITLE
Scannable failed to load correctly

### ISSUE THREAD

**Issue by JockyRhonson** [MightyPirates/Scannable#122]
I have the full crash log here, if someone could tell me what's up and what i need to do that would be awesome.

log:

[latest.log](https://github.com/MightyPirates/Scannable/files/10560617/latest.log)

**Comment by Klausthorn** [comment]
I also got this. I circumvented it by using an older version of scannable.

Error:

java.lang.NoClassDefFoundError: dev/architectury/platform/forge/EventBuses
		at li.cil.scannable.common.forge.CommonSetupForge.<init>(CommonSetupForge.java:12) ~[scannable-MC1.19.2-forge-1.7.7+dc5ea09.jar%23166!/:?] {re:classloading}
		
Version of scannable with error: scannable-MC1.19.2-forge-1.7.7+dc5ea09

Version of scannable **without** error: scannable-1.19.2-forge-1.7.7+1e13ff1.jar

Version of Forge: forge-1.19.2-43.2.0-installer.jar

Version of Minecraft: 1.19.2

**Comment by Cape-City** [comment]
I also got trouble with the latest version under fabric:

![grafik](https://user-images.githubusercontent.com/122229367/228343601-9458f4ed-8544-4125-ac0f-6215d94dd656.png)

The Version 1.7.7 works fine so far.

**Comment by fnuecke** [comment]
These generally seem to be due to either missing Architectury API mod (the declaration of that dependency may have been missing for a version or so, can't remember) or incompatible versions.  For the latter I'm afraid I don't have any suggestions besides "try to find one that works for all mods".
