### ISSUE TITLE
[Feature suggestions] Coordinates module, special blocks module, and config options.

### ISSUE THREAD

**Issue by NoMoreUsernames999** [MightyPirates/Scannable#124]
**I'm creating a space modpack for 1.12, and after discovering this awesome mod, I had an idea for an interaction between Scannable and Recurrent Complex. Pardon me if this version isn't receiving updates anymore, you can ignore my suggestion if so.** 

# Anyway, suggestions is as follows: 

## Suggestion 1:
Config option to add lists of coordinates with a dimension tag. The coordinate scanner module would then allow the scanner to ping these locations if in range and within the matching dimension. This use would be for modpacks that have static generation features, such as Recurrent Complex being able to always generate a structure at a fixed position. This could be used to more easily locate these unique structures, especially if they're buried! Would be useful for it to place the ping on the surface of the coordinate instead of a fixed Y coordinate to account for seed terrain variation between worlds, but not necessary. 

## Suggestion 2:
Module number two would be an additional special block module (beacon module? Maybe pinging these blocks will create an expanding circular "ping" visual effect?). Have a whitelist in the config for block ID, and instead of like with the targeted block scanner, this one will simply pick up all special blocks within range. Could be used by pack devs to give players a heads up about blocks of interest without the need for them to be specifically looking for it. Also alternatively serves as a way to locate structures if the above suggestion isn't possible (e.g could include custom beacon blocks in structures and add their ID to the whitelist).

## Suggestion 3:
Final suggestion would be the option to blacklist mobs from both entity type scanners, for if devs don't want players to see certain hostile mobs or make them harder to find (jump scares would be impossible otherwise :P Or maybe make a second tier for "stealthy" mobs?). 

Anyway, really cool mod, love the effects! Hope you consider at least the second suggestion. The visual effects of scannable really fit a space aesthetic. If 1.12 isn't updated anymore, maybe people could still use these in newer versions, though worse structure capabilities in newer versions would probably make the first suggestion useless. Except maybe for map makers.

**Comment by fnuecke** [comment]
Sorry for the late reply.  This is a little too special case for what I currently have the time to invest into the mod and am able to maintain.  That said, for modpacks that would need such specialized scanner functionality, the mod does have an API to allow custom modules.  So a custom addon mod would probably be the better solution for this, IMHO.  Thanks for the kind words and your interest in the mod though!
