### ISSUE TITLE
Scannable is installed but adds no items

### ISSUE THREAD

**Issue by malapro2** [MightyPirates/Scannable#125]
Title

**Comment by Acarys** [comment]
Same problem. I installed forge correctly and dragged the mod in the mod folder it doesn't affect the game at all. It doesn't cause the game to crash, doesn't load the mod, nothing. It just has no affect on the game whatsoever..

**Comment by fnuecke** [comment]
Too little information.  If you still have this issue in the latest MC versions, open a new ticket with more information (MC version, launcher, mod version, did you try it without other mods installed, exact steps to reproduce/observe, ...)
