### ISSUE TITLE
[1.18.2 Forge] Effect doesn't show up on server

### ISSUE THREAD

**Issue by infraaaa** [MightyPirates/Scannable#126]
When I use the scanner on a server, the charging animations play as normal but no effects show up (the scanning wave itself and the resulting scanned blocks / entities / whatever). When I use it on singleplayer, the effects show. 

[The config file](https://pastebin.com/m0w59QQL)
[Client mods](https://pastebin.com/Q51Y7dZp)
[Server mods](https://pastebin.com/hMxTAt0s)

**Comment by fnuecke** [comment]
I'm afraid I don't have time to support versions for older MC versions, sorry!
