### ISSUE TITLE
Scan view is shaped badly at high coordinates

### ISSUE THREAD

**Issue by Fuyukai** [MightyPirates/Scannable#127]
By high coordinates, I mean about a third of the way to the recently added hard barrier.

You can see the effects [here](https://i.imgur.com/LRI8nEJ.png). It jitters around a lot when turning so I assume this is probably standard floating point errors.

**Comment by fnuecke** [comment]
Yep, sure is floating point fun.  That said, since MC's PoseStacks use floats, not much I can do about that I don't think, sorry.

**Comment by Fuyukai** [comment]
Fair enough!
