### ISSUE TITLE
[1.20.1 Fabric] No wave effect

### ISSUE THREAD

**Issue by harpuppy** [MightyPirates/Scannable#129]
Eye candy is missing, block outlines & all other features seem to work fine. Thought it might be a compatibility issue but after launching a new world with only the mod & its dependencies installed, all latest versions, the problem persisted.

**Comment by fnuecke** [comment]
Needs more info, I'm afraid.  Tested with the following and everything works as expected:
- Scannable 1.7.8
- Fabric 0.87.0
- Architectury 9.1.12
- Forge config port 8.0.0
