### ISSUE TITLE
`Scannable requires version [0.87.0+1.20.1, 0.87.0+1.20.1] of fabric-api, which is missing!`

### ISSUE THREAD

**Issue by SettingDust** [MightyPirates/Scannable#132]
There is 0.88 fapi. But Scannable strictly require 0.87

**Comment by AzulConspirator** [comment]
[scannable fabric.mod.json](https://github.com/MightyPirates/Scannable/blob/1.20.1/fabric/src/main/resources/fabric.mod.json)
odd since this seems to be correct

**Comment by fnuecke** [comment]
Hmm, dependency should have been greater or equal, might have tagged a commit too early or so.
Will make a new release with >= 0.88 soon, adjusted in b77b069bb9da17410bea9ee19e1a6b143f28485d.
