### ISSUE TITLE
Conjuring 1.20 possible Incompatibility 

### ISSUE THREAD

**Issue by AzulConspirator** [MightyPirates/Scannable#133]
Conjuring 1.0.28 cause Scannable Block Highlight not to work.

[Modlist.txt without Conjuring] (https://github.com/MightyPirates/Scannable/files/12539937/Modlist.txt)

**Comment by fnuecke** [comment]
I'm afraid I don't have the time to look into specific mod incompatibilities  I'm not doing anything super-esoteric for the effect, just injecting a render call where all other MC level stuff is rendered, so my best guess is that the mod in question is somehow compromising the depth buffer before this mods rendering happens.
