### ISSUE TITLE
[1.20.1] Unexpected slots (with crash)

### ISSUE THREAD

**Issue by TheSnowyChickens** [MightyPirates/Scannable#136]
Hello,

there are 3 ghost slots and inserting an item on one of these slots let the game crash.

![image](https://github.com/MightyPirates/Scannable/assets/29357962/288b61d1-d3fa-43c3-b2da-23e98f708952)

Crash log:
[crash-2023-09-21_00.42.57-client.txt](https://github.com/MightyPirates/Scannable/files/12678141/crash-2023-09-21_00.42.57-client.txt)

Multiplayer or Singleplayer: Multiplayer, but the crash is only client side
MC: 1.20.1
Loader: Forge
Scannables: forge-1.7.9+b77b069
Architectury: 9.1.12 - forge
+ 57 more mods on the client and less on the server.

**Comment by fnuecke** [comment]
Thanks a lot for reporting!
