### ISSUE TITLE
[1.10.2-1.3.1.18] Crash when scanning for Diamond Ore and TF Platinum Ore

### ISSUE THREAD

**Issue by SPMoo66** [MightyPirates/Scannable#17]
A friend used two block modules to scan for Diamond Ore and Thermal Foundation's Platinum Ore. On their own, neither module caused a problem and scanned properly. When used together (both in scanner at the same time), the game crashes.

https://pastebin.com/Gdvu4yby

We also tried Gold Ore + Diamond Ore, but did not crash.

**Comment by fnuecke** [comment]
Thanks for reporting! Should be fixed with 3227bc6be245e30b080775294ae2580d17f3448a (1.3.2, pushing to Curse now).
