### ISSUE TITLE
Request :: Module storage within scanner

### ISSUE THREAD

**Issue by Temil2006** [MightyPirates/Scannable#18]
I really really like this mod. it's not to Overpowered, and also not to underpower. however, I do have 1 small request that would help greatly. 

Could you add a "storage" to the scanner, to store all the different modules that you make? Kind of like how you have the current "Active" mods on the scanner, just a field below it that starts with 1 space, and it expands everytime you add 1 mod to it that is used for storage of Mods for the scanner only. would help alot of keeping the different mods sorted out. would want to make sure it only allowed storage of mods, similar to the Tconstruct pattern storage system.

also, would be nice if you could put a stack of blank Module into the scanner, and as you find new Ore ..you  do a specific key or action, etc and it would use up one of the blank modules and make it into a specific ore module. this could work well with a storage of modules I stated above, and maybe even have it first check to see if you allready have one of those exact resource modules created allready.. and if you do, it would not use the resources to crap it, as you allready have it.

just a few thoughts is all ;)

**Comment by fnuecke** [comment]
Storage in as of be1db39d68263a38b4605509191957eb6958d5e8 (version 1.4).

As for the configuring of the block modules without having to take them out... adding an extra keybind for that feels like a bit much, tbh, and overloading sneak behavior or such would be a little... clunky. It'd also add custom behavior for one single module when in the scanner, which I don't really like. Maybe I'll add it some day, in a more generic form, but for now, not.
