### ISSUE TITLE
[1.4.0.2] Crash With Latest Forge

### ISSUE THREAD

**Issue by Kris1432** [MightyPirates/Scannable#20]
Forge: 2387
Version: 1.4.0.2

Cause: Starting up game causing the crash.

Crashlog: https://pastebin.com/bWLsHWdL

edit: redid this report to make more sense and something to work from. I'm sure you're aware that you need to update your mod to the latest version of forge, now that there is a recommended version of forge available, you should be able to go ahead and do that.

**Comment by Kris1432** [comment]
bump for completing bug report properly.

**Comment by fnuecke** [comment]
Fixed in 1.4.0.4!
