### ISSUE TITLE
When selecting ic2 uranium ore with the block module it sets it to basalt

### ISSUE THREAD

**Issue by Forecaster** [MightyPirates/Scannable#21]
Basalt is `ic2:resource#0` while uranium ore is `ic2:resource#4` so it doesn't recognize the meta-data.

**Comment by fnuecke** [comment]
Hmm, that's odd. I [do store the metadata for configured blocks](https://github.com/MightyPirates/Scannable/blob/master-MC1.11/src/main/java/li/cil/scannable/common/item/ItemScannerModuleBlockConfigurable.java#L71). Will need to debug into that.,,

**Comment by fnuecke** [comment]
Bah. Turns out IC2 doesn't implement `damageDropped` on its multi-id-blocks for some reason, so the block -> item stack lookup failed. At least that meant it was only the tooltip that was wrong, scanning still worked correctly.
