### ISSUE TITLE
[1.4.0.4] Server Startup Crash

### ISSUE THREAD

**Issue by Kris1432** [MightyPirates/Scannable#22]
Forge: 2387
Version: 1.4.0.4

Cause: Crashes on Server Startup

Crashlog: https://pastebin.com/6QuhzKbY

**Comment by captcookie** [comment]
https://pastebin.com/N7Z4d1jX

**Comment by fnuecke** [comment]
Huh, appears the `SideOnly` annotation is no longer inherited... that's... good to know ^.-

Thanks for letting me know. Fix coming shortly.

**Comment by fnuecke** [comment]
Fixed in 498523e7974020f708d1106c5965b9e85a2cbec6, version 1.4.0.5.
