### ISSUE TITLE
Feature Request: Exposed Ore / Line of Sight Setting

### ISSUE THREAD

**Issue by TwitchtvCarbs** [MightyPirates/Scannable#23]
A neat feature if at all possible that would be neat to have is when using the ore modules to only be able to ping the blocks that are exposed to the player. This could be used to make it so players can't just use it to find all the ores without having to dig at least a little. Perhaps have a setting for how far in depth the scanner would show from the exposed face of the ores or something?

Just an idea, personally for my own pack I've actually just turned off the ore modules because it seems a little cheaty so having an option to make it a little more fair would be really cool!

Keep up the great work though, love the mod and that great animation every time I use the scanner!

**Comment by fnuecke** [comment]
I like the idea, but it's non-trivial to implement this efficiently. I have some ideas how it could be done, but it'll take... quite a bit of time. First I'd have to adjust a scanline floodfill to overfill by a specific depth (to not only scan the surface), then I'd have to make it 3D. No promises if/when I'll get around to that.

For the time being, you can always lower their range ;)

**Comment by fnuecke** [comment]
While I had some ideas for this, it's generally too complex and complicated to be worth it I'm afraid.
