### ISSUE TITLE
[1.12] Creative tab leak

### ISSUE THREAD

**Issue by TheSaucyWelshman** [MightyPirates/Scannable#24]
Vanilla/Forge changes are causing items to show up in tabs they're not supposed to, and causing the scanner to show up in the creative trash slot. [Here](https://www.reddit.com/r/feedthebeast/comments/6h9z7f/psa_the_creativetab_leak_glitch/) is a thread on reddit about how to fix it.

**Comment by fnuecke** [comment]
Thanks for reporting, fixed in 1.4.1!

**Comment by TheSaucyWelshman** [comment]
Great! Thanks for the fix and the awesome mod. :)
