### ISSUE TITLE
Config Custom Ore

### ISSUE THREAD

**Issue by RainbowSaber** [MightyPirates/Scannable#27]
Custom Ores cant be added to the Ore filters

Geolosys adds Ores, that cant be added to the oreDict, a config option, that allows to add non oredict Ores to your filters would alleviate that problem.

**Comment by fnuecke** [comment]
Right, how about a list of block name + property values, e.g. `ic2:ore[type=copper]`, that would work, yes?

**Comment by RainbowSaber** [comment]
As long as the property value is optional that would be perfect (some of the Geolosys ores can drop several kinds of Ore (ex: Lead/Silver) so they couldnt be "assigned" to an existing oreDict ore.

**Comment by fnuecke** [comment]
Yeah, properties would be optional of course. Cool, I'll get to it then.

**Comment by RainbowSaber** [comment]
Just a small note: MetaData could be important in some cases

**Comment by fnuecke** [comment]
That's what the properties are for. They're just metadata in readable form.

**Comment by RainbowSaber** [comment]
Sure, makes sense
