### ISSUE TITLE
[Request] Compatibility With popular energy API

### ISSUE THREAD

**Issue by devilunaworkshop** [MightyPirates/Scannable#3]
Forge Power is still not well implemented in some mods. Would be great if the mod itself came with a bit of backward compatiblity with popular energy API's.

**Comment by fnuecke** [comment]
I take it you mean RF, specifically?

**Comment by devilunaworkshop** [comment]
I think if it could take RF it would be compatibile with Thermal / Immersive Engineering / Railcraft / Extra Utils gens? Or am i getting how API's in minecraft work wrong? (need to get back to java someday to fork some fun things)

**Comment by fnuecke** [comment]
3ad37de602565c5f33b9ea0f620c10e0d396b619

For 1.10. In 1.11 mods IMHO should really move to the Forge API already. I'd rather that gets pushed than dragging around the old API for much longer.
