### ISSUE TITLE
Crash when hovering over block module after scanning draconium

### ISSUE THREAD

**Issue by darkphan** [MightyPirates/Scannable#30]
Scannable Version: 1.12-1.6.1.12

Crashlog: https://pste.me/#/GIhX3

**Comment by fnuecke** [comment]
Relates to [this one](https://github.com/MightyPirates/BedrockOres/issues/36), waiting for a response from DE dev before I take action.

**Comment by fnuecke** [comment]
c734b9df978aab6651b4f32ef3a74da2f721f284 -- v1.6.2
