### ISSUE TITLE
Crash When Selecting Certain Blocks To Scan For

### ISSUE THREAD

**Issue by Darkosto** [MightyPirates/Scannable#31]
Hello, 

When selecting certain blocks like the following Astral Sorcery block the game crashes when hovering over the block selector upgrade:

https://pastebin.com/vwpvHXXB

Scannable: 1.7.1.12
MC: 1.12.1
Forge: 2485

Thank you!
Darkosto

**Comment by fnuecke** [comment]
Gah, so DE are not the only ones to do weird/fancy things in their getPickBlock method :P Will see if I can work around this.

**Comment by fnuecke** [comment]
c734b9df978aab6651b4f32ef3a74da2f721f284 -- v1.6.2
