### ISSUE TITLE
Allow the ORE scanner to differentiate between block metadata

### ISSUE THREAD

**Issue by Rosethorns** [MightyPirates/Scannable#37]
the following is a picture to illustrate the issue
![image](https://user-images.githubusercontent.com/2171914/37259793-e0719370-25ef-11e8-9fd0-c6674e8dc041.png)
on the left is Geolosys Coal
follow by vanilla coal
to the right is Beryl (emerald)
and behind is vanilla emerald.

Geolosys coal and geolosys beryl both share. Geolosys:ore_vanilla, separated by block state 
![image](https://user-images.githubusercontent.com/2171914/37259814-26b5b0be-25f0-11e8-8d8f-11d359ff84a4.png)
![image](https://user-images.githubusercontent.com/2171914/37259817-2ebbaaf2-25f0-11e8-9250-8662b1a04dc8.png)
Which can be expressed as meta 0 and 1

However. Geolosys Coal is ore dict as oreCoal and Beryl is ore dict as oreEmerald
![image](https://user-images.githubusercontent.com/2171914/37259829-63fd7556-25f0-11e8-880f-3b8bc3301006.png)
![image](https://user-images.githubusercontent.com/2171914/37259833-6c87e774-25f0-11e8-9d0d-670c672c5698.png)

The issue here is that the ore scanner only seems to care about the block sans state or meta
and as seen in the first picture Beryl shows up as coal according to the scanner.
This is true of any geolosys:ore_vanilla regardless of ore dictionary. (in this example)

Which leads me to believe that when scanning, the scan only confirms that a block is geolosys:ore_vanilla and finds the first ore dict for it, it can.

**Comment by fnuecke** [comment]
Ah yes, the ever returning joy of there not being a reliable static way of getting an item stack for a block in Minecraft (and in extension, a block's ore dictionary id). I've changed the way the lookup is built now -- basically this now uses the same method as is used to generate the tooltip of the configurable block module. This should work with most mod blocks, though it may still fail for some. New version is up, 1.6.3.
