### ISSUE TITLE
Internal Exception

### ISSUE THREAD

**Issue by Josral** [MightyPirates/Scannable#40]
I'm having an 'Internal Exception: java.nio.channels.ClosedChannelExcetion' and Scannable appears to be involved.  I have a world crash when I first start a minecraft session whether creating a new world or entering an existing world. Only happens once then I can get into the world.  This is single player. When I disable Scannable-MC1.12-1.6.3.17 or use the previous version the world crash does not occur. The log I have to look at is attached.
[Minecraft log.txt](https://github.com/MightyPirates/Scannable/files/1920799/Minecraft.log.txt)

**Comment by fnuecke** [comment]
Pretty sure this was the same as #42 and #43, try the latest version.
