### ISSUE TITLE
OpenGL Error

### ISSUE THREAD

**Issue by Xiaminou** [MightyPirates/Scannable#41]
When I use the Scanner for the first time it freezes my game for about 10s and throws this error.

![2018-04-16_17 21 10](https://user-images.githubusercontent.com/8670392/39193103-130d03de-47db-11e8-8739-9e6df8abffc9.png)

Minecraft: 1.12
Forge: 2669
Mods: [list.txt](https://github.com/MightyPirates/Scannable/files/1943120/list.txt)

**Comment by fnuecke** [comment]
Back when I tested it the mod did play nice with Optifine, but could you please see if this also happens when you disable/remove Optifine? Thanks.

**Comment by fnuecke** [comment]
Did some OptFine related fixes, assuming this is fixed until further feedback.
