### ISSUE TITLE
Debug output causing connection timeouts and long world load times

### ISSUE THREAD

**Issue by justinrusso** [MightyPirates/Scannable#43]
#### Description
I know this is a dupe, but the OP of the other issue (#42) made a mess and I'd imagine this would be a bit better.
This Scannable update caused a massive amount of lag on first join of a world. This seems to be related to a massive IO time on the network thread caused by this mod due to the amount of logging.

It appears as though the following is the cause: https://github.com/MightyPirates/Scannable/blob/18985c2c84521a046aafa2e4052bfb44eff9e05f/src/main/java/li/cil/scannable/util/BlockUtils.java#L40-L44

#### Suggested Solutions
Could this debug output maybe be a config option? This caused a massive time increase (15s+ for SevTech) to the world join times. Many players were experiencing connection timeouts.

In addition, it appears as though you store all states with `Set<IBlockState>` I assume to not log duplicates.
1. This appears to never be cleared
2. I assume it may be lighter on RAM if the ID of the blockstate was stored rather than the entire object

#### Workaround
For the time being, downgrading to 1.12-1.6.2.13 fixes the issue.

#### Versions
**Minecraft:** 1.12.2
**Forge:** 14.23.3.2655
**Scannable:** 1.12-1.6.3.17

**Comment by ofseaandstars** [comment]
I can confirm I'm also experiencing this.

World starts loading, hangs with no terrain showing, then crashes to the multiplayer menu (even if it was on Singleplayer) and loading worlds after that seems to work just fine.

**Comment by InjuredWolf** [comment]
downgrade to v13 for the time being. Revelation has.

**Comment by fnuecke** [comment]
Added a setting and disabled this logging by default, will push a new version momentarily.

Thought debug was disabled by default, sorry about that.

**Comment by justinrusso** [comment]
Thanks @fnuecke! One problem though... you never check if `logBlockDropLookupFailures` is true or false

**Comment by fnuecke** [comment]
I'm an idiot. This happens when you try to quick fix stuff right before going on vacation. Will properly fix when I get back tomorrow, sorry!

**Comment by fnuecke** [comment]
Allright, new version is being processed!
