### ISSUE TITLE
Cannot set colors for specific ores

### ISSUE THREAD

**Issue by guillaumearm** [MightyPirates/Scannable#45]
I cannot set colors for my specific nickel ores : 

![image](https://user-images.githubusercontent.com/16897658/40866518-52d67d4c-65fe-11e8-8df1-193994753975.png)

It still appear as default ores.

Maybe adding a S:statesColors config property ? ;-)

**Comment by fnuecke** [comment]
In 1.15 there's now options for separate per block and per block tag colorings.

Only took over two years!
