### ISSUE TITLE
Don't render a durability bar if "energyCapacityScanner" is set to 0

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MightyPirates/Scannable#46]
I disabled the RF consumption for Scannable in my pack. The max energy capacity of the scanner is set to 0, along with the energy cost of using every module. The scanner can't use or store RF.

There's an annoying black bar under the scanner. It's not needed, and I have a feeling it will annoy people.

**Comment by fnuecke** [comment]
I'd wager you didn't set the `useEnergy` setting to false. As long as that's true, it doesn't matter what numbers you configure, it'll still show the bar.
