### ISSUE TITLE
Screen freezed when using the scanner

### ISSUE THREAD

**Issue by nizhuan-jjr** [MightyPirates/Scannable#47]
I’m using the newest version of Scannable(1.6.3.19), and yes, I'm using an Optifine shader here. 
The screen will freeze when I use a scanner with its loading at 100%. After this, the game still runs with sounds, and I still perform actions in blind. FastRendering is off, 
The screenshot(grabbed by pressing F2, proved that the game was still running)：
![2018-08-21_19 41 35](https://user-images.githubusercontent.com/3255986/44402783-4c0db400-a585-11e8-964e-06f64ed1351a.png)

**Comment by nizhuan-jjr** [comment]
Even if I returned to the main menu, the screen would still be the frozen image.

**Comment by nizhuan-jjr** [comment]
This is the log file. I switched to the shader BSL v7.1p at 21：14, then used the scanner, and then the screen got frozen.
[latest.log](https://github.com/MightyPirates/Scannable/files/2306396/latest.log)

If I don't use any shader but with Optifine being active, the scanner would be able to run normally. Adding any shader would lead to the problem.

**Comment by fnuecke** [comment]
Ah, an internal name in OptiFine the integration depended on changed. Should no longer freeze (tested with SEUS). Thanks for letting me know.
