### ISSUE TITLE
Scanner just showing bars on screen

### ISSUE THREAD

**Issue by corgiblu** [MightyPirates/Scannable#49]
This might be related to #41 but for some reason suddenly whenever I tried to scan it would progress through the bar, and then it would cover my screen with the blue lines like when it's scanning but it took up the whole screen. The scanning then finishes and the bars go away. 
![2018-08-24_10 01 07](https://user-images.githubusercontent.com/32643374/44589732-4bdd0680-a787-11e8-84c8-950d570b6ff5.png)

Sometimes it gives me the same OpenGL error as issue 41 (1286), sometimes it doesn't. I was trying to figure out what mod was causing it to behave like this but when making a new instance and dropping mods I added/updated recently it still works okay. It was working when I first installed it, but seems to not want to work.

Log in case you need it: uhh. Sorry about this but my log was really long and so I didn't want to attach that one, (I had kept trying it), but now the game keeps crashing when I try to go into a world. So uh... I'll try to get a log later. I'm sick of just loading up the game only to watch it crash and stop responding.

Mod list: modlister.com/beanaboston

**Comment by fnuecke** [comment]
Are you using Optifine and which version of it? If so, could you tell me your settings (at least the ones that are not on their default values). What graphics card do you have?

**Comment by corgiblu** [comment]
I tested it in another instance and I know the optifine settings were the same, i'm going to check the rest of the settings. I have foamfix and betterfps as well. Not sure if those would cause any issues. I forgot to add betterfps to my testing, so i'll check that too. I'll report back in a little bit.

**Comment by corgiblu** [comment]
Alright. All my settings between the two instances I tested are the same. The one with all the mods I'm using is still broken, the one with the visual mods isn't. I'm using the same versions of all the mods.
Optifine: HD E2 Ultra
Foamfix: 0.10.1-1.12.2
BetterFPS: 1.4.8
So it's gotta be one of the mods I added or updated recently. OH! Could a forge update cause this? I think the 2 instances are different versions of forge. I'll test it later.

**Comment by corgiblu** [comment]
Made both instances version 14.23.4.2758 of forge and the one with a few mods still work properly. I guess I'll start going through half of them at a time to figure out what mod is breaking it.

**Comment by corgiblu** [comment]
All right. So I did a half and half test until I got it narrowed down to one mod, CreativeCore!

That seems to be the mod that causes the rendering issue.
Here's a log: https://paste.ee/p/Bxv5P

**Comment by fnuecke** [comment]
Thanks for narrowing it down, this helps a lot! I'll take a look.

**Comment by fnuecke** [comment]
Right, looks like this happens when the stencil component of the depth buffer has been enabled, which CreativeCore enforces...

Working on fixing stencil buffer support now.

**Comment by fnuecke** [comment]
And fixed. You can close the issue you opened on the CreativeCore repo.

**Comment by corgiblu** [comment]
All right thanks!
