### ISSUE TITLE
[1.10.2-1.0.0.3] Scan effect does not play

### ISSUE THREAD

**Issue by SPMoo66** [MightyPirates/Scannable#5]
When I use the scanner the scan effect does not play. The game freezes up until the effect would end, then displays ores like it normally would.

A video of the issue -
https://u.nya.is/uihmaa.mp4

If I can provide any other information that would help with this, ask. I realize that this alone probably doesn't help. :/

**Comment by devilunaworkshop** [comment]
Does it play on the surface? From my experience, in close spaces the effect moves too fast to notice sometimes (I only seen the effect in long caves underground, and barely at the end (about 20 blocks at least)

**Comment by SPMoo66** [comment]
No, it's just always a freeze, even on surface.

**Comment by fnuecke** [comment]
Pretty sure all that freezes is the rendering, I'm guessing something doesn't like that I'm swapping the depth buffer for a depth texture while the effect renders. Could you check your log for warnings or errors, just in case?

What graphics card do you have?

Does it also break if you're in a new world with nothing else equipped (might be an incompatibility with some other mod's rendering logic)?

Is this a generally available modpack? Then I could try to reproduce it.

**Comment by SPMoo66** [comment]
Log throws tons of GL errors -
https://pastebin.com/19iDSpGD
Journeymap incompatibility?

Graphics card is a GT 750M (laptop card).

Fresh world, same problem.

It's a private modpack that I'm working on, but I can draw up a list of mods or upload it for you if you need it.

**Comment by fnuecke** [comment]
Thanks! I hope that'll be enough to get me started, I'll grab JourneyMap and see if I can reproduce it.

(Though I did throw the mod into All The Mods for a quick compat check, which should have JM, but that was 1.11... will see.)

**Comment by fnuecke** [comment]
Hmm, doesn't appear to be JM itself, at least I can't reproduce with it alone. Probably some mod that renders between Scannable and JM that errors. If it's not too much of a hassle, could you try to boil it down to the one mod/set of mods that causes it? Good old binary search (remove first half of mods, see if it breaks, if it still does it's one in the latter half otherwise vice versa, repeat until minimal set remains).

**Comment by fnuecke** [comment]
(Actually, please try without any other mods first, not that it's just MC lying to me about having an FBO.)

**Comment by fnuecke** [comment]
Also, could you please test again with [the latest dev build](http://ci.cil.li/view/Scannable/job/Scannable-MC1.10/), I've thrown in some OpenGL error checking, if it's actually coming from within Scannable that would help narrowing it down.

**Comment by SPMoo66** [comment]
Using the newest version on its own (with JEI) works.

Newest version with the same modpack still doesn't work, but shows the effect over the entire screen now (with freezing).
http://i.imgur.com/o659F17.jpg
Same errors are being thrown, with a Scannable note this time
https://pastebin.com/YWWnf2u8

I'll work down the list and try to find out what's causing incompatibilities and report back later.

**Comment by SPMoo66** [comment]
Immersive Engineering [0.10-57] is the mod causing the problem.

**Comment by fnuecke** [comment]
Hmm, any other mods still active when switching IE in and out made a change? Because with just Scannable, JEI, IE (and with and without JourneyMap) it still works fine here :(

Just to narrow down some more variables: what Forge version are you using? Since it *is* a shader effect, have you tried updating your drivers?

**Comment by SPMoo66** [comment]
I used JEI+Scannable+ImEng together in one instance.

My forge version is a bit old, and I'm sure my video card drivers are old too. I'll update and try again when I get home later.

**Comment by Darkosto** [comment]
Just started working with this mod on stream and ran across the same issue:

[14:33:16] [Client thread/WARN] [scannable]: [OpenGL Error: 1286] Pre rendering: Invalid framebuffer operation

I'm on 1.10.2, Forge: 2281, latest Nvidia Drivers, 980ti card

**Comment by fnuecke** [comment]
Thanks! Let's see if I can reproduce with that version...
Edit: sadly, I cannot. This will be fun \o/

**Comment by SPMoo66** [comment]
Updated everything, no dice. Forge 2281, Nvidia drivers 382.05, etc.

**Comment by Darkosto** [comment]
@fnuecke What info can I give you help locate where the problem is?

**Comment by fnuecke** [comment]
@SPMoo66 I feared as much, thanks for trying tho!

@Darkosto With the current version, that's kinda difficult. It appears that something somewhere tries to interact with the FBO in a way that breaks when I plug in the depth texture; which is odd. The "Pre rendering" means something before my render code runs resulted in that error. Sadly, OpenGL errors aren't very... detailed.

I'm throwing some more logging in there and am looking into an alternative rendering method as a worst-case fallback (which would be slower, but at least it'd work...)

**Comment by fnuecke** [comment]
OK, let's see if this does anything. Could you please grab [the latest build from Jenkins](http://ci.cil.li/view/Scannable/job/Scannable-MC1.10/) and see if that fixes itself? Might flicker once in the first scan. If it doesn't, please try setting the config setting `injectDepthTexture` to `false`.

**Comment by SPMoo66** [comment]
That version works! It fails the initial render still, but the fallback works.

**Comment by fnuecke** [comment]
> the fallback works

Yay!

> It fails the initial render still

As in you have to change the config or it's just the first time it renders the effect that doesn't show correctly? Would really like the automatic fallback to work, so in case people want to add it to modpacks they don't have to choose the less performant option just to make sure it works for everyone.

**Comment by SPMoo66** [comment]
It fails the initial render as in "Might flicker once in the first scan."
The first scan I did basically did nothing, but every other one after that worked. No config changes necessary.

`[17:51:55] [Client thread/INFO] [scannable]: Huh, looks like our injected depth texture broke something maybe? Falling back to re-rendering.`

^that pops up in the log on the first scan attempt.

**Comment by fnuecke** [comment]
Okidoke. Thanks for confiming :)

Was asking because it should have fixed itself during the first scan already, will see if I can work that out, but if not that'll have to do.

Edit: ah, just saw the edit. Hmm, if it got in there... it should have worked. Odd.

**Comment by fnuecke** [comment]
d05826ee623ec92c8fe7423989c408d9f312c60d

Tried to stabilize that. If it still only starts working on the second scan, oh well. Another time. Thanks again for testing reporting and testing the fallback!
