### ISSUE TITLE
Game freezes (and doesn't unfreeze) occasionally when using the scanner

### ISSUE THREAD

**Issue by myrriad** [MightyPirates/Scannable#50]
Modpack: Enigmatica 2 Expert
Mod Version: 1.6.3.22

Game freezes and doesn't unfreeze (where I need to open task manager and kill Minecraft) occasionally when using the scanner.

The installed module doesn't seem to matter, and I can't reproduce it easily (other than "use the scanner repeatedly").
Admittedly this isn't a very helpful bug report, but I just want to document that a bug exists.

Edit: I didn't get a log.

**Comment by lateuponarrival** [comment]
[latest.log](https://github.com/MightyPirates/Scannable/files/3347478/latest.log)
Mod version 1.6.3.24
Same issue. Happens every single time I use the scanner. Tl;dr on the log, continually repeats 
[16:48:42] [Client thread/WARN]: GL Error in TileDrawStep: 1286
[16:48:42] [Client thread/ERROR]: ########## GL ERROR ##########
[16:48:42] [Client thread/ERROR]: @ Post render
[16:48:42] [Client thread/ERROR]: 1286: Invalid framebuffer operation

**Comment by fnuecke** [comment]
Apologies for the prolonged absence.

Probably some mod interaction breaking the OpenGL state; don't have plans on supporting the pre 1.15 versions though, sorry.
