### ISSUE TITLE
LinkageError (Crash)

### ISSUE THREAD

**Issue by artdude543** [MightyPirates/Scannable#51]
Heyo!

A developer of SevTech here. While testing a new beta build of the pack, this crash occurred https://pastebin.com/dSB54Awm Would it be possible for you to take a gander at this one?

Versions:
- Mod: 1.6.3.22
- Forge: 14.23.5.2772

Thanks!

**Comment by fnuecke** [comment]
Hm, can't reproduce this with just Scannable, maybe one of the coremods causing a hiccup? When do you get this, right when starting Minecraft I'm assuming? (Tested starting and using the scanner once, no crash with just Scannable)

**Comment by artdude543** [comment]
Dark got the crash when streaming. I was not watching so can't help on what was going on. But it could be a core mod issue. Not many updated from our last release, and I monitor the changelogs and didn't see anything from the ones that did. But you can't trust changelogs.

I'll see about if Dark can repro the issue on his next play test/dev.

**Comment by fnuecke** [comment]
OK, sorry for the super delayed response on this. So the me from back then was an idiot. This is on the server, where that code shouldn't even run... fixed that! Thanks for reporting, and again, sorry for the delay.

**Comment by artdude543** [comment]
He he no worries. Thanks for the fix! Much appreciated ❤️
