### ISSUE TITLE
[Request] The ability to define new block scanner modules with an array of blocks

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MightyPirates/Scannable#52]
In my pack, stones like marble and slate spawn in rare but large spheres. I'd like to create a scanner that detects those stone types.

Here's what I'd like to be able to do:
1. Create a new scanner item, either using ContentTweaker or a config
2. Supply a texture if a config is used
3. Define a list of blocks that the scanner would detect

**Comment by fnuecke** [comment]
I'm sorry, but I feel this is a little too specific to justify the amount of work it'd need to implement this.

As an alternative I'd suggest adding custom recipes (via one of those tweaker mods, however they're called nowadays), to craft block modules that are preconfigured. Basically `/give Player scannable:module_block 1 0 {"block":"iron_block", "meta":0}` as a recipe. If you need this for blocks with multiple states (i.e. non-zero meta values), I could probably add a way to specify the properties as key-value pairs, to avoid having to hardcode the number.

**Comment by TheDeviantCrafter** [comment]
I guess that could work. Would it be possible to create a single block scanner module with multiple blocks stored? This could be available in survival mode, so the payoff would probably be easier to justify.

**Comment by fnuecke** [comment]
Block and entity modules have been reworked to support (regular) configuration of up to 5 targets. Not sure if changing the icon can be done via data packs or such, but at least the "multiple custom targets" is now possible. Additionally, they can be defined/spawned in a locked state where they cannot be reconfigured. E.g.: `/give @p scannable:module_block{blocks:["minecraft:coal_ore"],isLocked:true}`
