### ISSUE TITLE
Some warning using the mod on a Mac

### ISSUE THREAD

**Issue by Saereth** [MightyPirates/Scannable#53]
```
[23:29:35] [Client thread/ERROR] [scannable]: Failed loading shader.
java.lang.Exception: ERROR: 0:1: '' : version '130' is not supported
```

this was reported first on our tracker where there is more information.
https://github.com/Vyraal1/FTB-Interactions/issues/282

This may be a nonissue, not really sure so we're passing it on to you to decide
if we can gather any additional information for you let us know, thanks

**Comment by fnuecke** [comment]
After digging for a bit it appears Apple has pretty... substandard OpenGL support in general. In this specific case the problem most likely is their lack of support for compatibility profiles, meaning one can't mix OpenGL versions. Something that is supported fully on Linux and Windows.

So my guess is that there are these two possibilities: their Minecraft runs using OpenGL 2 or OpenGL 4.

Here's a [resource pack with OpenGL 2 shaders](https://github.com/MightyPirates/Scannable/files/2776071/shaders120.zip). Have them try that. Note that unless using Scannable MC1.12.2-1.6.3.23 or newer they'll have to restart MC after activating the resource pack (I added shader reloading on resource reload in that version). If that doesn't work (presumably with `version '120' is not supported`) they're probably running OpenGL 4, for which it is a bit more complicated to port the shaders for, and will need code changes as far as I'm aware. Something I don't have the time for right now I'm afraid.

**Comment by ghost** [comment]
Applied texture pack, here is a log:
[latest.log](https://github.com/MightyPirates/Scannable/files/2794812/latest.log)

**Comment by fnuecke** [comment]
Sorry for the long absence; I'm not planning on supporting the pre MC1.15 versions anymore. If this still happens in the latest versions, please let me know.
