### ISSUE TITLE
Scan for Immersive Engineering excavator veins

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MightyPirates/Scannable#55]
Using the core sample drill is a long, manual process that gets old pretty quickly. I'd like to be able to use Scannable for this task.

The mod randomly gives each chunk ore veins. It can have 0 ore veins, or occasionally up to 5.

Here's how I would handle it:

1. Create two upgrades: one for ores, and one for liquids (water/lava/oil)

2. When scanned, the veins will show up as glowing objects sitting at or just below the bedrock layer

3. If multiple veins are found, place them all next to each other. It would look like someone replaced pieces of bedrock with a few different types of ore and then scanned it with the ore scanner.

**Comment by Boolyman** [comment]
I was coming here to recommend this

**Comment by fnuecke** [comment]
As the silence may have indicated, I'm afraid I don't have the time. The API should allow doing this in an integration mod though.
