### ISSUE TITLE
[Suggestion] Scan for multiple blocks with a single block scanner module

### ISSUE THREAD

**Issue by TheDeviantCrafter** [MightyPirates/Scannable#57]
There are quite a few cases where I'd want to scan for several blocks at once. Modded stone types, Botania flowers, Forestry trees, etc. Since the scanner only has three slots, and each block scanner can only detect a single block type, the scanner doesn't really work for cases like this.

I'd like to be able to store several blocks in a single block scanner module.

**Comment by fnuecke** [comment]
Block and entity modules have been reworked to support (regular) configuration of up to 5 targets.
