### ISSUE TITLE
"Block module" does not differentiate between ores with different Meta

### ISSUE THREAD

**Issue by the-vindex** [MightyPirates/Scannable#59]
If I assign Block module an ore which is differentiated by metadata, it is recorded correctly, but scanning itself does not differentiate it.

Example:
Magneticraft Wolframite <magneticraft:ores:3>
=> Block module data: <scannable:module_block>.withTag({meta: 3, block: "magneticraft:ores"})
Magneticraft Pyrite <magneticraft:ores:4>
=> Block module data: <scannable:module_block>.withTag({meta: 4, block: "magneticraft:ores"})

But when I assign Pyrite and scan, Wolframite AND Pyrite are highlighted.

**Comment by fnuecke** [comment]
Sorry for the prolonged absence; I don't plan on supporting version pre MC1.15 anymore. The way multiple blocks were encoded into one registered block did make things somewhat tricky. Luckily by now this is no longer how things are done (well, should be done) and each block type is registered as its own block. So issues like these should be a thing of the past in 1.15+.
