### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/Scannable#6]
There's been some requests for allowing to integrate the scanner in some other mods' modular gimmicks. Among those:

- [x] ~EnderIO dark steel armor~ From what I can see, no API. So meh.
- [ ] Blood Magic living armor
- [x] ~Modular Power Suits~ Might be added to MPS itself ([source](https://www.reddit.com/r/feedthebeast/comments/69fewy/new_mod_scannable/dh7v6x3/)).
- [x] ~Cyberware~ Available via [WIRED](https://minecraft.curseforge.com/projects/wired-more-augs).

Will have to look into their APIs.

**Comment by lehjr** [comment]
I finally got around to this for MPS 1.12.2.
