### ISSUE TITLE
Suggestion: Opacity Configuration

### ISSUE THREAD

**Issue by Boolyman** [MightyPirates/Scannable#60]
The highlight of blocks when using the Scanner Module: Block is very hard to see under certain conditions.  It woul be very helpful if you could add the option to change the color and/or opacity of the highlight "aura".

**Comment by fnuecke** [comment]
Not planning to update version pre MC1.15, but in the new version the highlight rendering has changed a bit and there's also a label for the focused results, which should help with this.

![2020-08-13_12 51 16](https://user-images.githubusercontent.com/514903/90171362-abcc7d80-dda1-11ea-932a-ecfbe184b4c3.png)
