### ISSUE TITLE
Underground Biomes Compatibility

### ISSUE THREAD

**Issue by Samrel556** [MightyPirates/Scannable#62]
When scanning for common ores with underground biomes installed it will only highlight the ores of each stone type with 0 for metadata even though they all are in the same ore dictionary.

All of the same ore in each stone type after using the scanner.

![coalOresAfterScanning](https://user-images.githubusercontent.com/18405229/66353718-f2e71800-e91f-11e9-8a1b-ae3f7ac8e726.png)

The ores are separated by stone type. Bottom are igneous stone. Middle is metamorphic stone. Top is sedimentary stone. Only one of each is highlighted. The one that is highlighted has a metadata value of 0

Here is what f3 says for the first two blocks on the bottom.

![redGraniteCoalOreBlockInfo](https://user-images.githubusercontent.com/18405229/66353894-6ab54280-e920-11e9-9f0e-7d438f894385.png)
![blackGraniteCoalOreBlockInfo](https://user-images.githubusercontent.com/18405229/66353919-786ac800-e920-11e9-87e6-3e03a881da38.png)

They have the same internal name with the only thing differentiating them being their metadata as shown on the item tooltip.

![redGraniteCoalOreItemInfo](https://user-images.githubusercontent.com/18405229/66353975-a6500c80-e920-11e9-96e6-4b58a4478163.png)
![blackGraniteCoalOreItemInfo](https://user-images.githubusercontent.com/18405229/66353976-a819d000-e920-11e9-93e0-20b026daac16.png)

They are both part of the same ore dictionary.

It seems that the mod is failing to get the ore dictionary for underground biomes blocks with metadata values greater than 0.

This zip file has more pictures showing the same data for the other stone types, modlist, config files, and logs. [Scannable.zip](https://github.com/MightyPirates/Scannable/files/3699924/Scannable.zip)

**Comment by fnuecke** [comment]
Sorry for the prolonged absence; I don't plan on supporting version pre MC1.15 anymore. The way multiple blocks were encoded into one registered block did make things somewhat tricky. Luckily by now this is no longer how things are done (well, should be done) and each block type is registered as its own block. So issues like these should be a thing of the past in 1.15+.
