### ISSUE TITLE
Locking modules for pack makers

### ISSUE THREAD

**Issue by Dr-Mic** [MightyPirates/Scannable#64]
I want to give a block scanning module for a specific block as a quest reward. The problem is that they can just take that module, go right click a diamond ore block(or other rare block), then skip things that shouldn't be skipped. So a feature like a lock icon that once pressed cant be undone or a new module meant for this?

**Comment by fnuecke** [comment]
Block and entity modules can now be defined/spawned in a locked state where they cannot be reconfigured. E.g.: `/give @p scannable:module_block{blocks:["minecraft:coal_ore"],isLocked:true}` (for the entity module it's `entities:[...]`).
