### ISSUE TITLE
[Suggestion] Color blind mode

### ISSUE THREAD

**Issue by MoeHunt3r** [MightyPirates/Scannable#66]
Hey there! 
It would be really awesome if you would add something like a color blind mode. 
I know some people who are color blind and when they are scanning for ores they don't see the color difference for each ore.

**Comment by fnuecke** [comment]
While I'm not planning on backporting this to pre MC1.15, there's now also labels for focused block results which should help with this in the future.

![2020-08-13_12 51 16](https://user-images.githubusercontent.com/514903/90170152-e2a19400-dd9f-11ea-905a-106493a2bf6e.png)
