### ISSUE TITLE
[Request] 1.16.3 update

### ISSUE THREAD

**Issue by 3x1at1on** [MightyPirates/Scannable#70]
Can you be kind to update this mod to 1.16.3 please?

**Comment by fnuecke** [comment]
The mappings still have quite a few holes, so porting right now would involve a lot of pointless work.
So for the moment, I won't be releasing a "proper" 1.16.3 version, sorry.

However, if #68 was the only issue, the 1.16.2 build might work just fine in 1.16.3.
