### ISSUE TITLE
Galacticraft-Ore / Scanner (From Scannable) Issue

### ISSUE THREAD

**Issue by XIPure** [MightyPirates/Scannable#73]
Hi,
I've just been disabling ore generation for Copper/Tin/Aluminum Ore in the Galacticraft-Core configs via the "core.conf" file in the Galacticraft folder in the Configs folder and when I booted up the instance (..via MultiMC) and went into a newly generated world just now, the ores are not spawning which is good / how it should be but when I scan for Galacticraft-Specific Copper/Tin/Aluminum Ore with the Scanner + Block Module, it for some reason manages to pickup/detect Galacticraft specific Silicon Ore which is still enabled in the config-file / aka untouched.

This first image is Me scanning for Copper Ore, the blue parts however, are Silicon Ore which is completely different to Copper, obviously, lol. I knew it was Silicon Ore because I had started digging My way to that location (In-Game) after taking the screenshot below and then I saw that it said "Silicon Ore" on The One Probe's In-Game tooltip.
![image](https://user-images.githubusercontent.com/47751365/102046713-c35d5680-3dd3-11eb-9fdb-ce2e35580f49.png)

This second image is Me doing the same exact process but with Galacticraft Tin Ore showing very similar locations and/or the exact same locations (The blue parts) which are Silicon Ore. I had yet again checked this by digging My way to that location in-game and checking via The One Probe tooltip.
![image](https://user-images.githubusercontent.com/47751365/102046816-04ee0180-3dd4-11eb-9254-18e1f965c3bd.png)

After having used the World Stripper mod to clear away stone/etc.... on a newly generated world, I was able to do some more scanning specifically with Copper Ore and Tin Ore (again), I was able to verify most of what I've explained above, please read the images below:
![image](https://user-images.githubusercontent.com/47751365/102047586-68c4fa00-3dd5-11eb-895a-734d3445cf02.png)
![image](https://user-images.githubusercontent.com/47751365/102047624-7d08f700-3dd5-11eb-9602-2a5839473cc6.png)

All of this was done on a newly generated world, twice. I've also spoke with someone called ROM™ from the Galacticraft Discord Server who has said/confirmed (Or assumes) that it's an issue with Scannable when I had thought it was Galacticraft's fault at first because I assumed the ores (Copper/Tin/Aluminum) were still generating after having disabled them, haha lol.

Hopefully I've explained all of this clearly and hopefully it can be fixed soon if at all! :D 👍
I look forward to a reply.

Thanks!
-XIPure

**Comment by XIPure** [comment]
Update:
Upon further testing in newly-generated worlds, I am noticing that, when scanning Galacticraft-Core's Copper/Tin/Aluminum, it's mostly Silicon Ore that's being detected, but it's also Silicon Ore AND Boron Ore (From NuclearCraft) sat right next to each other sometimes, might just be a coincidence that they tend to spawn near each other a lot when generated but I just thought it would be worth it to mention/show this.

Example/Proof:
![image](https://user-images.githubusercontent.com/47751365/102171922-99696a00-3e8f-11eb-94da-4ecaa320807a.png)

**Comment by fnuecke** [comment]
I'm guessing either blockstate differentiation is broken, or they do something fancy with their ores. I'll have a look when I can.

Mind posting the exact versions you're playing with? Thanks!

**Comment by XIPure** [comment]
@fnuecke Yeah sure 👍 That's fine with Me, haha. Here are the details You requested =)

Minecraft Version: 1.12.2
Launcher/Version: MultiMC 0.6.11-1430
Galacticraft-Core Version: 1.12.2-4.0.2.280
Galacticraft-Planets Version: 1.12.2-4.0.2.280
Scannable Version: 1.6.3.24

**Comment by XIPure** [comment]
Hi again @fnuecke :)
I was just wondering if You had been able to do some testing regarding the issue above?
If so, will it be a nice quick and easy hotfix? Haha 🤞
Thanks!

**Comment by XIPure** [comment]
Any updates?

**Comment by fnuecke** [comment]
Yeah, took a bit to get a 1.12 workspace up and running a gain, and to get Galacticraft inside it (much easier to debug that way). But it's fixed now! Will be on Curse momentarily.

**Comment by XIPure** [comment]
Can confirm I have not come across any Galacticraft Copper/Tin/Aluminum Ore thus far on the latest version/hotfix that was pushed to CurseForge which is good!😄


Thank You very much for resolving/fixing this issue! ❤️
