### ISSUE TITLE
Scanner highlighting box instead of the block itself

### ISSUE THREAD

**Issue by deevo1** [MightyPirates/Scannable#74]
I'm not sure if this a bug at all or it was already fixed, but when I scan for viaducts it highlights a box with all the blocks inside. I'm trying to find where all my viaducts are so seeing where they are specifically would be helpful.

Gif:
![scannable](https://user-images.githubusercontent.com/74677035/102538715-a1393200-407a-11eb-83d3-097b5d9a4d3d.gif)

Versions of things:
Scannable: 1.6.3.24
Forge: 14.23.5.2854
Thermal Dynamics: 2.5.5.21
Minecraft: 1.12.2

**Comment by deevo1** [comment]
Also does the same for fluxducts and ae2 cables.

**Comment by fnuecke** [comment]
Yeah, this is a limitation of how results are rendered in MC1.12. It's the bounding box.

This has been refined in MC1.16 but uses new tech, so there won't be a backport, I'm afraid.
