### ISSUE TITLE
1.16.4 Crash on dedicated server

### ISSUE THREAD

**Issue by zjdtmkhzt** [MightyPirates/Scannable#75]
Using version 1.7.1,7 on a dedicated server.

I had a block scan module with Cobblestone, Stone, Coal Ore set.
I tried to open it to remove some of the set blocks, but could not figure out how to do it.
I tried to maybe replace the blocks with other blocks, so I took a Stone block from my inventory and clicked on the Stone block that was displayed in the Block Scan Module UI.
This caused the Server to crash with a StackOverflowError.

Side note:
The mod does not seem to be properly working for us, we use the scanner (with modules set, we tried both block scan and fluid scan) and it does the little circle animation, but it does not do the animation of the scanning wave flying out, and no blocks or fluids are highlighted.
So perhaps there is some larger issue there.

**Comment by fnuecke** [comment]
Could you please add the crash log? Thanks.

I've fixed the server crash caused by the block module UI, but I don't see any StackOverflowErrors or such.

**Comment by zjdtmkhzt** [comment]
Thanks, I will check to see if I can reproduce it in single player when I have time, as I think my server owner would not appreciate me trying it on the live server.^^

I may have accidentally written StackOverflow even though it was an ArrayIndexOutOfBounds thing, I probably misremember, but I will check later.

**Comment by zjdtmkhzt** [comment]
I think I was just confused, because it was kind of too many items in a stack, so my mind just went to stackoverflow, but I don't think it was actually a stackoverflow error, so I think I'll close this, since the newest version apparently fixes it, thanks!

**Comment by fnuecke** [comment]
Allrighty, glad to hear it!
