### ISSUE TITLE
Renderer freezes when scanning while certain shaders are active, 1.16.4, Optifine HD 6G Ultra Pre-release 2

### ISSUE THREAD

**Issue by Syampuuh** [MightyPirates/Scannable#77]
Tested with only Optifine and Scannable, the renderer seems to freeze when it activates. I can hear the game proceeding and give inputs, but no new frames are drawn. Even blindly disconnecting to the main menu, I'm still looking at the same frame. Tested with BSL, Sildur's, and SEUS PTGI; SEUS PTGI and Optifine's "internal" shader do not have the issue, but BSL and Sildur's do. I also double checked with the two most recent release versions of Optifine, but there was no change.

Here's the debug log:
[debug.log](https://github.com/MightyPirates/Scannable/files/5761045/debug.log)

And a video of the issue:
https://streamable.com/m2gyo5

This appears like it could be a recurrence of #47.

**Comment by Syampuuh** [comment]
Wanting to continue to use the mod alongside shaders, I tested a small pile of popular shaders to see what does and doesn't work.

Out of what I tested, in addition to the internal shader and SEUS PTGI, the following shaders don't have any issues (at least in their default configurations, I didn't configure them much or at all):

- Beyond Belief Shaders
- Vanilla Plus Shader
- Tea Shaders
- Nostalgia Shader
- projectLUMA Shaderpack
- RGB Shaders (Yes, really, unfortunately)

Everything else pictured here in my list had the same freeze.
![2021-01-04_17 26 08](https://user-images.githubusercontent.com/25516124/103590030-72acbb00-4eb2-11eb-9ddd-6d31d92ddf8a.png)
(Unique exception to NV Shaders, where the screen completely blacks out rather than having the same frame stuck; the rest of the symptoms still apply though)

I should also note that I did this test in a superflat world of just stone, with nothing for the scanner to highlight. And, come to think of it since this is a shader issue, I'm running the game on Nvidia hardware, a 3080, with the most recent drivers, 460.89. Hopefully this all helps narrow things down, or at least helps others find alternative shaders to use.

**Comment by F0x06** [comment]
Had the same issue, version `1.7.2.15` fixed the issue for me.

**Comment by fnuecke** [comment]
That version did have a fix for the scan effect breaking in MC's own "Fabulous" rendering mode. If someone could confirm whether or not this also fixed the issues mentioned above, that'd be appreciated, thanks.

**Comment by F0x06** [comment]
> That version did have a fix for the scan effect breaking in MC's own "Fabulous" rendering mode. If someone could confirm whether or not this also fixed the issues mentioned above, that'd be appreciated, thanks.

The "wave" effect was broken (missing) for me using BSLex shaders and also without shaders or optifine on version 1.7.2.15.

**Comment by jackg2527** [comment]
> That version did have a fix for the scan effect breaking in MC's own "Fabulous" rendering mode. If someone could confirm whether or not this also fixed the issues mentioned above, that'd be appreciated, thanks.

I can confirm freeze fix. 1.16.4 with Sildur's Enhanced default shaders, Optifine HD U G6 + around 80 other mods. With Scannable v1.7.1.10 the game froze right when I clicked to scan. Updated to 1.7.3.16 and all good. The cool wave effect is missing with shaders on, but ancient debris is eye candy to me! And thank you for the great mod, dunno how many hours it has added back to my life...but it's a lot!

**Comment by F0x06** [comment]
> > That version did have a fix for the scan effect breaking in MC's own "Fabulous" rendering mode. If someone could confirm whether or not this also fixed the issues mentioned above, that'd be appreciated, thanks.
> 
> I can confirm freeze fix. 1.16.4 with Sildur's Enhanced default shaders, Optifine HD U G6 + around 80 other mods. With Scannable v1.7.1.10 the game froze right when I clicked to scan. Updated to 1.7.3.16 and all good. The cool wave effect is missing with shaders on, but ancient debris is eye candy to me! And thank you for the great mod, dunno how many hours it has added back to my life...but it's a lot!

Exactly, and yes this mod is the ultimate time saver to find those difficult ores! Can't play without it now :) also using it to discover chests in strongholds is godlike :P.

About the wave effect I'll contact the dev of BSLex to see if this wave effect can be restored, if you disable shaders the wave effect is working for you?

**Comment by jackg2527** [comment]
> > > That version did have a fix for the scan effect breaking in MC's own "Fabulous" rendering mode. If someone could confirm whether or not this also fixed the issues mentioned above, that'd be appreciated, thanks.
> > 
> > 
> > I can confirm freeze fix. 1.16.4 with Sildur's Enhanced default shaders, Optifine HD U G6 + around 80 other mods. With Scannable v1.7.1.10 the game froze right when I clicked to scan. Updated to 1.7.3.16 and all good. The cool wave effect is missing with shaders on, but ancient debris is eye candy to me! And thank you for the great mod, dunno how many hours it has added back to my life...but it's a lot!
> 
> Exactly, and yes this mod is the ultimate time saver to find those difficult ores! Can't play without it now :) also using it to discover chests in strongholds is godlike :P.
> 
> About the wave effect I'll contact the dev of BSLex to see if this wave effect can be restored, if you disable shaders the wave effect is working for you?

I just tried it. Set shaders to OFF: still no wave effect, but ores are showing up as expected (same as with shaders on). One other thing I'm using forge 35.1.36. Previously had 35.1.13 + v1.7.1.10: game froze with shaders on but I'm pretty sure I DID see wave effect with shaders disabled. Happy to re-check this and/or send more info if it will help, just let me know. Cheers!

**Comment by F0x06** [comment]
> > > > That version did have a fix for the scan effect breaking in MC's own "Fabulous" rendering mode. If someone could confirm whether or not this also fixed the issues mentioned above, that'd be appreciated, thanks.
> > > 
> > > 
> > > I can confirm freeze fix. 1.16.4 with Sildur's Enhanced default shaders, Optifine HD U G6 + around 80 other mods. With Scannable v1.7.1.10 the game froze right when I clicked to scan. Updated to 1.7.3.16 and all good. The cool wave effect is missing with shaders on, but ancient debris is eye candy to me! And thank you for the great mod, dunno how many hours it has added back to my life...but it's a lot!
> > 
> > 
> > Exactly, and yes this mod is the ultimate time saver to find those difficult ores! Can't play without it now :) also using it to discover chests in strongholds is godlike :P.
> > About the wave effect I'll contact the dev of BSLex to see if this wave effect can be restored, if you disable shaders the wave effect is working for you?
> 
> I just tried it. Set shaders to OFF: still no wave effect, but ores are showing up as expected (same as with shaders on). One other thing I'm using forge 35.1.36. Previously had 35.1.13 + v1.7.1.10: game froze with shaders on but I'm pretty sure I DID see wave effect with shaders disabled. Happy to re-check this and/or send more info if it will help, just let me know. Cheers!

Yes, that confirms what I've seen, same behavior

**Comment by fnuecke** [comment]
Sorry, as the prolonged silence may have indicated, I don't have the time to dig into shader mod intercompatibility issues anymore.
