### ISSUE TITLE
[1.16.4] Server start failed, mod loading error has occurred.

### ISSUE THREAD

**Issue by Gbergz** [MightyPirates/Scannable#78]
Title ^
Sometimes when the server starts it crashes. 
"Mod loading error has occurred", while this doesn't happen 100% of the time it does happen sometimes. And when it does happen it could do it 2 times in a row. Or even more.

**Minecraft:** 1.16.4
**Forge**: 35.1.28
**Scannable:** [1.7.1.10](https://www.curseforge.com/minecraft/mc-mods/scannable/files/3148866)

# Crash Report
https://hatebin.com/qrpdadfpab

**-** Gbergz

**Comment by fnuecke** [comment]
Thanks for reporting this! Should be fixed in the next version.
