### ISSUE TITLE
[Suggestion]A few ideas to extend the uses and integrations of the scanner.

### ISSUE THREAD

**Issue by Corvus20** [MightyPirates/Scannable#84]
A scanner accessory for when curios is installed:
Just a small idea I head, unsure how easy it would be to implement. This would be a curio for most likely the goggles or back slot (depending on you'd rather go the scanner visor or radio backpack-style approach). A keybind can be pressed and held to charge up the scanner, improvements including a slightly longer default range, increased power capacity, and more storage for inactive scanner cards.

A more specialized mob scanner:
This could also be a curio, but the main idea is that it would be toggled on or off. It would frequently emit shorter range + duration pings that would highlight hostile mobs. While the item is on, it will continuously use power until it is turned off. Could be fun for more "scary" modpacks with limited minimap capabilities, creepier mobs, and enhanced darkness.

Scanner Relay:
A curio for other players to equip. Allows them to see what other player's scanners detect, allowing for more cooperation during mining and exploration of structures/dungeons

Optional "barebones" ping icons: small, red upwards triangles for hostiles, green downwards triangles for passives, orange squares for resources/blocks, and blue dots for structures. Making smaller, less "in your face" icons would likely be appreciated by many players.

**Comment by fnuecke** [comment]
There's an API that allows triggering scans and registering additional result providers. This sounds like it would better go into a separate integration mod :)
