### ISSUE TITLE
No way to un-register a block from Block Scanner Module

### ISSUE THREAD

**Issue by ghost** [MightyPirates/Scannable#86]
It would be a very nice QoL feature to have, say, sneak-use the module to clear its registered blocks.

**Comment by fnuecke** [comment]
In 1.16 the module has a UI that allows removing configured blocks (and adding them using block items).
Sadly this is not easily possible in pre 1.16 and I don't plan on updating the older versions, anyway.
So, if you're stuck on pre 1.16, I'm sorry, but that's how it'll stay.

**Comment by ghost** [comment]
My apologies, I don't know how I missed that.

**Comment by Xetaxheb** [comment]
It might be worth changing the tooltip of the module to note right-clicking air. It seemed strange there wasn't a way and I didn't consider this (**right clicking air**) before searching this in the issue tracker.

**Comment by fnuecke** [comment]
Fair point.

**Comment by JustJinxed** [comment]
Can we revisit maybe adding this tooltip to the 1.16 branch? I just spent days trying to figure this out and feel so silly as to have missed this, lol.
