### ISSUE TITLE
[Compatibility Issue] Compact Ores are all Rare and display full namespace name

### ISSUE THREAD

**Issue by ellbristow** [MightyPirates/Scannable#88]
The scanner doesn't seem to know what to do with ores from the CompactOres mod. It classes them all as Rare Ores (which I guess in a sense is true) but it would better if it just ignored them, since they are always with their non-compact counterpart... plus the naming of them in the UI is Janky

**Comment by fnuecke** [comment]
In that case, please add them to the list of ignored blocks in the config.
