### ISSUE TITLE
Scanner Module: Entity

### ISSUE THREAD

**Issue by VallenFrostweaver** [MightyPirates/Scannable#9]
Similar to the block module you could find a specific entity (hostile or not) by clicking on it as well (handy for finding wither skeletons, ghasts, witches, specific villagers in a village, etc.).

**Comment by fnuecke** [comment]
Hmm, I originally thought this'd be redundant with the animal and monster scanners, but I suppose there are enough "select" monsters one would hunt for to make this worthwhile. Might also make this to be configured by using the module on the mob, would make it very... interesting to configure it to stuff like ghasts >:3

**Comment by fnuecke** [comment]
7c9000e4c2d626aef36c15c13238290d7bb2701b
