### ISSUE TITLE
[Feature Request] Item scanning

### ISSUE THREAD

**Issue by AngleWyrm10** [MightyPirates/Scannable#91]
Scenario:
Setting up a mob farm, but it doesn't work because somewhere nearby I've placed a [Torchmaster](https://www.curseforge.com/minecraft/mc-mods/torchmaster) spawn prevention torch. But I no longer remember where that is.

How this mod could help:
An Item Detection module, that adds/enables a GUI slot for inserting an item to detect in the world.

**Comment by fnuecke** [comment]
Been a while. Not sure what the state was back then, but the block module should be able to help with that (configuring it to the placed block, to just scan for it).
