### ISSUE TITLE
[Question] How to search for custom structures

### ISSUE THREAD

**Issue by DevTimur** [MightyPirates/Scannable#93]
There is a mod "[Ruins (Structure Spawning System)](https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system)" and it spawns structures.
Is it possible to search for that structures using structure card?

**Comment by fnuecke** [comment]
I'm afraid structure scanning is no longer supported due to performance issues (no non-blocking/chunk-generating way for checking for structures).
