### ISSUE TITLE
[1.17.1] Mod incompatibility with construction wands.

### ISSUE THREAD

**Issue by ProsperCraft** [MightyPirates/Scannable#94]
https://github.com/Theta-Dev/ConstructionWand/issues/37

**Comment by Theta-Dev** [comment]
The crash that @ProsperCraft experienced was caused by faulty ItemHandler code in my mod. I have fixed the bug in the new version.

So you can close this issue, there are no problems with your mod.

**Comment by ProsperCraft** [comment]
Solved on Construction wand side.
