### ISSUE TITLE
"stack is null"

### ISSUE THREAD

**Issue by BrandedEvil** [MightyPirates/Scannable#95]
Every time I go to look for the way to create it on my hardcore world, my game crashes and it gives me this message:
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.ItemStack.m_41720_()" because "stack" is null
Exit Code: -1
I am on 1.17.1, the latest Forge that there is at this time, and this is my only mod that I have installed.
Hopefully this issue can be fixed soon.

**Comment by fnuecke** [comment]
I'm afraid there's nothing I can do here without a full log.
