### ISSUE TITLE
Dual type (mob + entity etc) scanner crashes if already scanning, then makes world unlaunchable

### ISSUE THREAD

**Issue by NighthowlerStudios** [MightyPirates/Scannable#96]
1.16.5, latest scannable mod, forge 36.2.x

Before world locks out:
https://pastebin.com/BgE4dWjx

Then it proceeds to make the world unlaunchable because:
https://pastebin.com/k87r6Ap5

Please help, as this world is important for my youtube playthrough!

**Comment by NighthowlerStudios** [comment]
Seems to be specific to the Mob scanner being used in unison with Entity scanner, but only locks the player out if the scan is interrupted by leaving the world.

**Comment by NighthowlerStudios** [comment]
And no, these are not render issues, I know I have optifine installed. it's entirely server side code with the "lock out" issue, but the client side seems to be what caused the initial crash.

**Comment by NighthowlerStudios** [comment]
the unlaunchable thing is fixed by restarting the client.  it seems that the issue is only possible because of Not Enough Crashes mod still attempting to reload the server.

**Comment by fnuecke** [comment]
Sadly not possible to tell what the original cause of the error was with those logs, but added some safety nets to avoid it requiring a restart in the future.
