### ISSUE TITLE
Scanning doesn't work without energy

### ISSUE THREAD

**Issue by ghost** [MightyPirates/Scannable#99]
I'm playing on my Forge 1.18.1 server with some buddies.
The energy cost has been turned OFF in the config files, however...this doesn't seem to affect much to anything.
When I try to use the scanner, it only shows the loading-bar, but won't actually scan anything [no sound either].

IDK why this happens. 
Maybe a ''quick-fix'' would be to add an option for the "amount of Energy" the scanner has already at the start- [when it's created], this way it won't run out even if funky stuff happens in the code? IDK just a suggest :3

**Comment by fnuecke** [comment]
I'm afraid I cannot reproduce this.

Does this also happen in a singleplayer world?
Is there anything in the log files?

**Comment by MCPO-Spartan-117** [comment]
It seems scannable has a client desync problem in 1.19.2-1.7.7, the server has energy turned off but the client has it on, so the client can't use the scanner till it's turned off client-side.

**Comment by danusorn012** [comment]
Yes, I am using version 1.19.2-1.7.7 as well and I have the same problem. When setting the config on the client, it is necessary to set the config on the server to match as well. Instead of setting the config only on the server, is there a way to fix this?
